---
before:
  hooks:
    - go mod download

builds:
  - binary: kdummy
    id: kdummy
    goos:
      - linux
    goarch:
      - amd64
      - arm64

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
