---
before:
  hooks:
    - go mod download

builds:
  - binary: kdummy
    id: kdummy
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - binary: kdummy_mac
    id: kdummy_mac
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: desc
