---
before:
  hooks:
    - go mod download

builds:
  - binary: kdummy
    id: kdummy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  - image_templates:
      - ghcr.io/particledecay/{{ .ProjectName }}:{{ .Version }}-{{ .Arch }}
    dockerfile: Dockerfile
    goarch: {{ .Arch }}
    use: buildx
    build_flag_templates:
      - --platform={{ .Os }}/{{ .Arch }}
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/particledecay/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/particledecay/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
docker_manifests:
  - name_template: ghcr.io/particledecay/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/particledecay/{{ .ProjectName }}:{{ .Version }}-{{ .Arch }}
  - name_template: ghcr.io/particledecay/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/particledecay/{{ .ProjectName }}:{{ .Version }}-{{ .Arch }}
