---
# installation: `pre-commit install -t pre-commit -t commit-msg`
repos:
  - repo: https://github.com/talos-systems/conform
    rev: v0.1.0-alpha.23
    hooks:
      - id: conform
        entry: 'conform enforce --commit-ref refs/heads/main --commit-msg-file'
        stages:
          - commit-msg
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/Bahjat/pre-commit-golang
    rev: master
    hooks:
      - id: go-fmt-import
      - id: go-vet
      - id: go-lint
