apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.public.port }}
      targetPort: http
      protocol: TCP
      name: public-http
    - port: {{ .Values.service.internal.port }}
      targetPort: {{ .Values.service.internal.port }}
      protocol: TCP
      name: internal-http
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
