---
name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Cache Go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub release
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up dist directory if exists
        run: |
          rm -rf dist/

      - name: Update Helm chart version
        run: |
          sed -i "s/tag:.*/tag: ${GITHUB_REF_NAME}/" chart/values.yaml
          sed -i "s/version:.*/version: ${GITHUB_REF_NAME}/" chart/Chart.yaml
          sed -i "s/appVersion:.*/appVersion: ${GITHUB_REF_NAME}/" chart/Chart.yaml

      - name: Commit Helm version changes
        uses: devops-infra/action-commit-push@v0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_prefix: "chore: "
          commit_message: "helm chart version updated"
          target_branch: helm_version_update

      - name: Create PR for Helm version
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: helm_version_update
          target_branch: main
          title: update helm chart version to ${{ github.ref_name }}
          body: "** Automated pull request **"
          reviewer: particledecay
          label: enhancement
